# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b7936cbe0ea54417ede9dc70c029b3d358a9a526beeb522382f377c1e476db5a43960003f6754eaea19853279deba2cebc91bb6173ec3874914bf8a76cc9bb

test:
  secret_key_base: d99db95856f6af7208459d8dc722bea490b547c5bf814f53c2a6e5372c1cd1f2134d714dadedcdd0b7bce797eef2fef66796aa78f5736905f643bfe6e3cc99ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
